name: check_updates
on:
  schedule:
    # Check daily
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  check_updates:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'reubenmiller'
    env:
      CREATE_PR: 0
      PR_BRANCH: updater
    steps:
      - uses: actions/checkout@v4
      - name: Check update
        run: ./scripts/admin.sh update_version
      - name: Create PR on new version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          git add -A . ||:

          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes detected"
            exit 0
          fi

          LATEST_VERSION=$(./scripts/admin.sh latest_version)
          echo "Changes detected. Raising PR"
          git status
          git config --global user.email "info@thin-edge.io"
          git config --global user.name "Versioneer"

          if [ "$CREATE_PR" = 0 ]; then
            git commit -am "Update version to $LATEST_VERSION"
            git push --set-upstream origin main
          else
            git checkout -b "$PR_BRANCH"
            git commit -am "Update version to $LATEST_VERSION"
            git push --set-upstream origin "$PR_BRANCH"
            gh repo set-default ${{github.repository}}
            gh pr create --title "Update version: $LATEST_VERSION" --body "Update version"
          fi
